gitlab:
  image: gitlab/gitlab-ce:${GITLAB_DOCKER_TAG}
  restart: always
  hostname: git.cloud4africa.free.ci
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https:git.cloud4africa.free.ci'
      # Add any other gitlab.rb configuration here, each on its own line
      nginx['redirect_http_to_https'] = true
      letsencrypt['enable'] = true
      letsencrypt['contact_emails'] = ['${admin_email}']
      prometheus['enable'] = true
      prometheus_monitoring['enable'] = true
      unicorn['worker_processes'] = 1
      unicorn['worker_timeout'] = 60
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/data/gitlab/config:/etc/gitlab'
    - '/data/gitlab/logs:/var/log/gitlab'
    - '/data/gitlab/data:/var/opt/gitlab'
    
    
    NB: se mettre dans le dossier /svr/gitlab/
        pour lancer le docker-compose
