version: '2'
services:
  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner:latest
    volumes:
    - ./gitlab-runner-config:/etc/gitlab-runner:Z
    command:
    - register
    - --non-interactive
    - --locked=false
    - --docker-privileged
    - --name=ShellFactory Runner
    - --executor=docker
    - --docker-image=docker:20.10.5
    - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    environment:
    - CI_SERVER_URL=https://gitlab.com/
    - REGISTRATION_TOKEN=${gitlab_token}
    - DOCKER_AUTH_CONFIG={\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"XXXXXXXXXXXXXX\"}}}
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    depends_on:
      - register-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner-config:/etc/gitlab-runner:Z
    environment:
      - CONFIG_FILE=/etc/gitlab-runner/config.toml
